name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.0.0

      - name: set up JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.2

      - name: Install SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.5

      - name: Install NDK
        run: sdkmanager 'ndk;20.0.5594570'

      - name: Build with Gradle
        run: ./gradlew build

      - name: ktlint
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: ktlintCheck

      - name: detekt
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: detekt

      - name: Run Unit Tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: jacocoTestReportDebug

      - name: Codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODE_COV_TOKEN  }}
