name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.0.0

      - name: set up JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.2

      - name: Lint
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: ktlintCheck detekt

      - name: Install NDK
        run: sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: jacocoTestReportDebug

      - name: Codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODE_COV_TOKEN  }}
